project_id = "mfhsrbqximubjbjreicw"

[functions.generate-course]
verify_jwt = false

[functions.generate-course-bulk]
verify_jwt = false

[functions.regenerate-course-content]
verify_jwt = false

[functions.support-chat]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
